### ISSUE TITLE
Alpha 4 Roadmap

### ISSUE THREAD

**Issue by int-72h** [AdastralGroup/osprey#27]
This list exists internally but I decided to also put it here

- [x] Launching across all platforms 
- [x] install in another location
- [x] advanced panel with launch args / install path
- [ ] fixed all outstanding major bugs

**Comment by int-72h** [comment]
Launching fixed by #29!

**Comment by int-72h** [comment]
Installing in another location backend should be fixed by #32.

**Comment by int-72h** [comment]
size checks should be enabled and working with #33 merged.

**Comment by int-72h** [comment]
#38 tackles the advanced panel.

**Comment by int-72h** [comment]
> Installing in another location backend should be fixed by #32.

#32 merged (2 months late!)

**Comment by int-72h** [comment]
Pushing size checks back to Beta 1...

**Comment by int-72h** [comment]
IT'S OUT!
